### ISSUE TITLE
Unable to record DI signals

### ISSUE THREAD

**Issue by brandonStell** [acq4/acq4#128]
We are using an NI6229 and recording AI signals works fine. However we receive this error when adding a DI to the config:

```python
2022-01-28T15:32:17.966376+01:00 Error in task thread, exiting. 
acq4.util.HelpfulException.HelpfulException: 
Error starting task:
ValueError: Requested sample rate 40000 exceeds maximum (0) for this device.
Show traceback 9
```

our config:

```
# This configuration file defines a set of simulated devices that allow some 
# of ACQ4's acquisition capabilities to be tested on any machine. 
# 
# Also included are example configuration for every type of device supported
# by ACQ4, commented out. These may be used to construct a working 
# device configuration file.



# First, define the NI DAQ device we will use. For use with a real DAQ, simply
# remove the line 'mock: True'. The name 'DAQ', defined here, will appear
# many times throughout the config to refer to this device.
DAQ:
    driver: 'NiDAQ'
    mock: False# this is a fake device; remove this line for real NI DAQ devices.

    # Default mode for AI channels. Options are 'NRSE', 'RSE', and 'DIFF'
    # This may be overridden for individual channels.
    defaultAIMode: 'NRSE'

    # Default input/output voltage ranges


# A simple device connected to the DAQ that uses one AI channel and one AO 
# channel. As with all of the following device definitions, the name 
# 'DaqDevice' is arbitrary.
DaqDevice:
    driver: 'DAQGeneric'
    channels:
        AIChan:
            device: 'DAQ'
            channel: '/Dev2/ai0'
            type: 'ai'
        DIChan:
            device: 'DAQ'
            channel: '/Dev2/port0/line1'
            type: 'di'
```

From the 6229 datasheet:

![image](https://user-images.githubusercontent.com/11091919/151565452-64a163c3-35c1-40a3-9635-221defdf79bf.png)
