### ISSUE TITLE
teach Microscope to have presets

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#253]
put it in the config.

* teach microscope to discover all its light sources
* give all devices a chance to do "post-device setup" setup ("device-configured" signal? only children?)
* teach it to know its filters
* give optomech "optics" (e.g. transmitted, epifluorescent) labels on parent-child relationships (similar to filterset)
* maybe make a context manager that preserves previous states once the context is done

**Comment by outofculture** [comment]
presets can now be added to the Microscope config. they will look something like:
```
Microscope:
    presets:
        brightfield:
            Camera: '30fps'
            FilterTurret: '695um'
            SomeLightSource:
                channel: 'white'
                brightness: 0.9
            SomeOtherLightSource: 'off'
            hotkey:
                key: 10, 12
                device: 'Xkeys'
        fluoresce:
            ...

Camera:
    presets:
        30fps:
            ...
```
Give that a shot and let me know if it's confusing or non-functional.
