### ISSUE TITLE
Multiclamp 700B non-steady baseline

### ISSUE THREAD

**Issue by JRS92** [acq4/acq4#259]
I am using a NI USB 6343 and a Multiclamp 700B. Recording in either voltage-clamp or current clamp the signal ramps down for two seconds then remains at a steady state. The settings in the multi camp commander match what I see in ACQ4. I am not getting this issue with different acquisition software so I assume this has something to do with settings in ACQ4. Possibly an offset? 

 My config settings for DAQ and Clamp1 are:

```
DAQ:
    driver: 'NiDAQ'
    defaultAIMode: 'NRSE'
    defaultAIRange: [-10, 10]
    defaultAORange: [-10, 10]

Clamp1:
     driver: 'MultiClamp'
     channelID: 'model:MC700B,sn:00838628,chan:1'

     commandChannel: 
         device: 'DAQ'
         channel: '/Dev1/ao0'
         type: 'ao'
     primaryChannel: 
         device: 'DAQ'
         channel: '/Dev1/ai0'
         mode: 'NRSE'
         type: 'ai'
     secondaryChannel: 
         device: 'DAQ'
         channel: '/Dev1/ai4'
         mode: 'NRSE'
         type: 'ai'
     vcHolding: 0
     icHolding: 0.0
     defaults:   # Default amplifier state. The amplifier will be 
                 # reconfigured with these options every time ACQ4 is 
                 # started. 
         IC:
             HoldingEnable: False
             Holding: 0.0
             TestSignalEnable: False
             #SlowCurrentInjEnable: False
             NeutralizationEnable: True
             #OscKillerEnable: True
             PrimarySignalGain: 2
             PrimarySignalLPF: 20e3
             PrimarySignalHPF: 0
             OutputZeroEnable: False
             BridgeBalEnable: True
             BridgeBalResist: 15e6
         VC:
             HoldingEnable: False
             Holding: 0.0
             TestSignalEnable: False
             #SlowCurrentInjEnable: False
             #NeutralizationEnable: False
             WholeCellCompEnable: False
             RsCompEnable: False
             #OscKillerEnable: True
             PrimarySignalGain: 2
             PrimarySignalLPF: 20e3
             PrimarySignalHPF: 0
             OutputZeroEnable: False
             LeakSubEnable: False
```
